services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mic-authservice:local
    restart: unless-stopped
    environment:
      PROFILE: local
      SERVER_PORT: 8080
      SSL_ENABLED: "false"
      SERVER_COOKIE_SECURE: "false"
      SERVER_COOKIE_SAME_SITE: lax
      POSTGRES_URL: jdbc:postgresql://host.docker.internal:5401/db01
      POSTGRES_USER: user01
      POSTGRES_PASSWORD: pass01
      REDIS_HOST: host.docker.internal
      REDIS_PORT: 6379
      ISSUER_URI: http://localhost:6001
      HANDLER_URL: http://localhost:4200
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "6001:8080"
      - "8443:8080"