server:
  port: ${SERVER_PORT:6001}
  ssl:
    enabled: ${SSL_ENABLED:true}
    key-store: ${SSL_KEY_STORE:classpath:keystore.p12}
    key-store-password: ${SSL_KEY_STORE_PASSWORD:password}
    key-store-type: ${SSL_KEY_STORE_TYPE:PKCS12}
  servlet:
    session:
      cookie:
        same-site: ${SERVER_COOKIE_SAME_SITE:none}
        secure: ${SERVER_COOKIE_SECURE:true}
        http-only: true

spring:
  datasource:
    url: jdbc:postgresql://caboose.proxy.rlwy.net:56135/railway
    username: postgres
    password: HzqtSlLQcwdwWbPaKSelEdvsnUuKbhSo
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    enabled: true
  kafka:
    bootstrap-servers: crossover.proxy.rlwy.net:32058
    properties:
      schema.registry.url: http://schema-registry-sbs4-desarollo.up.railway.app
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: admin:admin123
    enabled: true
    consumer:
      auto-offset-reset: earliest
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:60000}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:6001}
app:
  security:
    handler-url: ${HANDLER_URL:http://localhost:4200}

logging:
  level:
    root: INFO
    "[org.springframework.security.oauth2]": TRACE
    "[org.springframework.security.web]": DEBUG
