-- ──────────────────────────────────────────────────────────────────────────────
-- NX036SHOP-482 — RBAC granular: tabla permissions + role_permissions.
--
-- Diseño:
--   • permissions: catálogo de permisos atómicos identificados por code (ej.
--     "orders:read", "products:write", "users:delete").
--   • role_permissions: join role↔permission. Un rol agrupa N permisos; un
--     usuario hereda permisos a través de sus roles existentes (user_roles).
--
-- Los servicios consultan `is_role_permitted(roleId, code)` para autorizar
-- endpoints anotados con @NxRequiresPermission. La función se cachea en
-- memoria (Caffeine TTL=60s) para no martillar el join por cada request.
--
-- Seeds mínimos: rol ADMIN obtiene todos los permisos catalogados; USER no
-- recibe permisos por defecto (sólo accede a sus propios recursos vía
-- ownership en SpEL).
-- ──────────────────────────────────────────────────────────────────────────────

--changeset authservice:1.21_rbac_permissions
CREATE TABLE IF NOT EXISTS permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(80) UNIQUE NOT NULL,
    category    VARCHAR(40) NOT NULL,
    description VARCHAR(200),
    enabled     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_permissions_category ON permissions(category);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    granted_at    TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    granted_by    VARCHAR(60),
    PRIMARY KEY (role_id, permission_id)
);

CREATE INDEX IF NOT EXISTS idx_role_permissions_permission ON role_permissions(permission_id);

-- Catálogo inicial de permisos (cubre verbos más comunes; añadir según
-- crecen los micros).
INSERT INTO permissions (code, category, description)
VALUES
    ('orders:read',     'orders',     'Listar y leer órdenes de cualquier usuario'),
    ('orders:write',    'orders',     'Crear/modificar órdenes en nombre de otros usuarios'),
    ('orders:cancel',   'orders',     'Cancelar órdenes (incluye refund automático)'),
    ('products:read',   'products',   'Leer productos (incluso ocultos)'),
    ('products:write',  'products',   'Crear y modificar productos'),
    ('products:delete', 'products',   'Eliminar / descontinuar productos'),
    ('users:read',      'users',      'Listar y ver perfiles de cualquier usuario'),
    ('users:write',     'users',      'Modificar perfiles ajenos'),
    ('users:delete',    'users',      'Borrar usuarios'),
    ('cms:write',       'cms',        'Editar contenido CMS (banners, campañas, gift cards)'),
    ('returns:approve', 'returns',    'Aprobar devoluciones y emitir refund'),
    ('analytics:view',  'analytics',  'Ver dashboards y reports administrativos'),
    ('rbac:manage',     'rbac',       'Asignar permisos a roles (super-admin)')
ON CONFLICT (code) DO NOTHING;

-- Otorga todos los permisos al rol ADMIN (siempre existe — seed inicial del
-- sistema). Si el rol no existe, no falla la migración.
INSERT INTO role_permissions (role_id, permission_id, granted_by)
SELECT r.id, p.id, 'system-bootstrap'
FROM roles r
CROSS JOIN permissions p
WHERE r.unique_name = 'ADMIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;
