create table if not exists grant_types (
    enabled BOOLEAN DEFAULT TRUE not null,
    id bigint generated by default as identity,
    name varchar(120) not null unique,
    primary key (id)
);

create table if not exists group_roles (
    group_id bigint not null,
    role_id bigint not null
);

create table if not exists groups (
    enabled BOOLEAN DEFAULT TRUE not null,
    id bigint generated by default as identity,
    name varchar(60) not null,
    unique_name varchar(60) not null unique,
    description varchar(500),
    primary key (id)
);

create table if not exists oauth_clients (
    id bigint generated by default as identity,
    client_id varchar(120) not null unique,
    client_secret varchar(120) not null,
    primary key (id)
);

create table if not exists oauthclient_granttypes (
    granttype_id bigint not null,
    oauthclient_id bigint not null
);

create table if not exists oauthclient_redirecturis (
    oauthclient_id bigint not null,
    redirecturi_id bigint not null
);

create table if not exists oauthclient_scopes (
    oauthclient_id bigint not null,
    scope_id bigint not null
);

create table if not exists redirect_uris (
    enabled BOOLEAN DEFAULT TRUE not null,
    id bigint generated by default as identity,
    name varchar(120) not null,
    value varchar(500) not null unique,
    primary key (id)
);

create table if not exists roles (
    enabled BOOLEAN DEFAULT TRUE not null,
    id bigint generated by default as identity,
    name varchar(60) not null,
    unique_name varchar(60) unique,
    description varchar(500),
    primary key (id)
);

create table if not exists scopes (
    enabled BOOLEAN DEFAULT TRUE not null,
    id bigint generated by default as identity,
    user_id bigint,
    name varchar(60) not null,
    unique_name varchar(60) not null unique,
    description varchar(500),
    primary key (id)
);

create table if not exists user_groups (
    group_id bigint not null,
    user_id bigint not null
);

create table if not exists user_roles (
    role_id bigint not null,
    user_id bigint not null
);

create table if not exists user_scopes (
    scope_id bigint not null,
    user_id bigint not null
);

create table if not exists users (
    account_non_expired BOOLEAN DEFAULT TRUE,
    account_non_locked BOOLEAN DEFAULT TRUE,
    credentials_non_expired BOOLEAN DEFAULT TRUE,
    enabled BOOLEAN DEFAULT TRUE,
    id bigint generated by default as identity,
    last_name varchar(60),
    name varchar(60),
    user_name varchar(60) unique,
    email varchar(120) unique,
    password varchar(250),
    primary key (id)
);