-- ──────────────────────────────────────────────────────────────────────────────
-- NX036SHOP-448 — 2FA TOTP (scaffolding).
--
-- Tabla user_totp: almacena el secreto TOTP por usuario, junto al status
-- (PENDING_VERIFICATION cuando el usuario aún no escaneó el QR; ENABLED tras
-- la primera verificación correcta; DISABLED si lo apagó).
--
-- recovery_codes: códigos one-shot (10 por usuario) que sustituyen el código
-- TOTP en caso de pérdida del autenticador. Se almacenan hasheados con bcrypt.
--
-- Aún NO se ata al flujo de login: el authorization-server seguirá emitiendo
-- tokens sin pedir el código. La activación del check vive detrás de la flag
-- `auth.totp.enforced=true` (default false).
-- ──────────────────────────────────────────────────────────────────────────────

--changeset authservice:1.22_totp_scaffolding
CREATE TABLE IF NOT EXISTS user_totp (
    user_id     VARCHAR(60) PRIMARY KEY REFERENCES users(unique_name) ON DELETE CASCADE,
    secret      VARCHAR(64) NOT NULL,
    status      VARCHAR(30) NOT NULL DEFAULT 'PENDING_VERIFICATION',
    last_used_at TIMESTAMP WITH TIME ZONE,
    enrolled_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    disabled_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS user_totp_recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(60) NOT NULL REFERENCES users(unique_name) ON DELETE CASCADE,
    code_hash  VARCHAR(120) NOT NULL,
    used_at    TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_totp_recovery_user ON user_totp_recovery_codes(user_id);
