-- Create permissions table
CREATE TABLE IF NOT EXISTS permissions (
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    unique_name VARCHAR(60) NOT NULL UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(120),
    updated_by VARCHAR(120),
    PRIMARY KEY (id)
);

-- Create join table for role_permissions
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT fk_role_permissions_role_id FOREIGN KEY (role_id) REFERENCES roles(id),
    CONSTRAINT fk_role_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id)
);

-- Create join table for group_permissions
CREATE TABLE IF NOT EXISTS group_permissions (
    group_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT fk_group_permissions_group_id FOREIGN KEY (group_id) REFERENCES groups(id),
    CONSTRAINT fk_group_permissions_permission_id FOREIGN KEY (permission_id) REFERENCES permissions(id)
);
