-- Tabla permissions
CREATE TABLE IF NOT EXISTS permissions (
    enabled BOOLEAN DEFAULT TRUE NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(60) NOT NULL,
    unique_name VARCHAR(60) UNIQUE,
    description VARCHAR(500),
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    created_by VARCHAR(120),
    updated_by VARCHAR(120),
    PRIMARY KEY (id)
);

-- role_permissions
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- group_permissions
CREATE TABLE IF NOT EXISTS group_permissions (
    group_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_group_permissions PRIMARY KEY (group_id, permission_id),
    CONSTRAINT fk_group_permissions_group FOREIGN KEY (group_id) REFERENCES groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_group_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

-- Eliminar user_scopes (scopes solo para clientes OAuth)
DROP TABLE IF EXISTS user_scopes;

-- Eliminar user_id de scopes
ALTER TABLE scopes DROP COLUMN IF EXISTS user_id;
