ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE groups ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE groups ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE groups ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE scopes ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE scopes ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE scopes ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE scopes ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE grant_types ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE grant_types ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE grant_types ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE grant_types ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE redirect_uris ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE redirect_uris ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE redirect_uris ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE redirect_uris ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

ALTER TABLE oauth_clients ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE oauth_clients ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE oauth_clients ADD COLUMN IF NOT EXISTS created_by VARCHAR(120);
ALTER TABLE oauth_clients ADD COLUMN IF NOT EXISTS updated_by VARCHAR(120);

UPDATE users SET created_at = NOW() WHERE created_at IS NULL;
UPDATE roles SET created_at = NOW() WHERE created_at IS NULL;
UPDATE groups SET created_at = NOW() WHERE created_at IS NULL;
UPDATE scopes SET created_at = NOW() WHERE created_at IS NULL;
UPDATE grant_types SET created_at = NOW() WHERE created_at IS NULL;
UPDATE redirect_uris SET created_at = NOW() WHERE created_at IS NULL;
UPDATE oauth_clients SET created_at = NOW() WHERE created_at IS NULL;
